name: Limelight Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run box version	    
      uses: docker://mriffle/build-limelight:latest
      with:
        entrypoint: ant
        args: -f ant__build_all_limelight.xml
